version: '3'

services:
  server:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - atha_db

  atha_db:
    image: postgres:14
    container_name: atha_db
    env_file:
      - backend/.env
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgres/data
