default_stages: [commit]

repos:
-   repo: local
    hooks:
    -   id: isort
        name: Running isort
        entry: isort
        language: system
        files: .*.py
        args: ["--profile", "black"]
        exclude: '^(migrations\/.*)$'
    -   id: black
        name: Running black
        entry: black
        exclude: '^(migrations\/.*)$'
        language: system
        files: .*.py
    -   id: flake8
        name: Running flake8
        entry: flake8 --count
        language: system
        files: .*.py
        exclude: '^(migrations\/.*)$'
    -   id: mypy
        name: Running mypy
        entry: mypy
        language: system
        files: .*.py
        exclude: '^(.*tests\/.*|migrations\/.*)$'
